# -*- coding: utf-8 -*-
"""modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pW-VOFFfTPl725Mej7gSOGZayOxNUun6

# **MODELING THE PROBLEM**

---

Let $x_{ij}$ be a binary decision variable where:

$x_{ij} = 1$ if the path from city $i$ to city $j$ is included in the travel from city $A$ to city $O$ , and
$x_{ij} = 0$ otherwise.

The objective function to minimize is the total distance of the path:

\begin{equation}
\text{Minimize} \sum_{i,j} d_{ij} \cdot x_{ij}
\end{equation}

Subject to the following constraints:

Ensure that there is zero or one outgoing edge from each inner city(except for A, O):

\begin{equation}
\sum_{j} x_{ij} = y_{j} \quad \text{for} \quad i \in \{B, C, D, E, F, G, H, I, J, K, L, M, N\}
\end{equation}

Ensure that there is zero or one incoming edge to each inner city (except for A, O):

\begin{equation}
\sum_{i} x_{ij} = y_{i} \quad \text{for} \quad j \in \{B, C, D, E, F, G, H, I, J, K, L, M, N\}
\end{equation}

where $y_{j}  \in \{0, 1\}$, and $y_{i}  \in \{0, 1\}$. Note that although it seems we used different notations for the number of outgoing and incoming edges from a city, they ( $y_{j}$ and $y_{i}$) are the same numbers for the same city. For example, if the number of outgoing edges from city $B$ ($j=B$) is $y_{B}$, so is that of incoming edges to city $B$ ($i = B$), which means $y_{j}$ and $y_{i}$ are the same numbers for the same city.


Ensure that the destination city has exactly zero outgoing edges:

\begin{equation}
\sum_{j} x_{Oj} = 1 \quad \text{for} \quad j \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

Ensure that the starting city has exactly zero incoming edges:

\begin{equation}
\sum_{i} x_{iA} = 0 \quad \text{for} \quad i \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

Ensure that the destination city has exactly one incoming edge:

\begin{equation}
\sum_{i} x_{iO} = 1 \quad \text{for} \quad i \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

Ensure that the starting city has exactly one outgoing edge:

\begin{equation}
\sum_{j} x_{Aj} = 0 \quad \text{for} \quad j \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}
\end{equation}

$x_{ij}$, $y_{i}  \in \{0, 1\}$,  $\quad \forall i,j \in \{A, B, C, D, E, F, G, H, I, J, K, L, M, N, O\}$

These constraints ensure that:

- There is exactly one path from the starting city to the destination city.
- There are no cycles in the path.
- Each city (excluding the starting and destination cities) may not necessarily be visited exactly once.

Solving this linear programming problem will give us the shortest path between the given cities both in terms of distances and likelikood of delays.

# Receiving and reading the data
"""

import numpy as np
from numpy import genfromtxt
# my_distances = genfromtxt('distance.csv', delimiter=',')
# my_delays = genfromtxt('delay.csv', delimiter=',')
# print(my_distances)
# print(my_delays)

"""# Creating the constraints"""

import numpy as np
from numpy import genfromtxt

my_distances = np.array([
    [ 0.,  0.,  0., 42.,  0.,  0.,  0., 59., 29.,  0.,  0., 25.,  0.,  0.,  0.],
    [ 0.,  0.,  0.,  8., 21.,  0.,  0.,  0.,  0.,  0., 25.,  0.,  0.,  0., 25.],
    [ 0.,  0.,  0.,  0.,  0.,  0., 31., 62.,  0., 11.,  0.,  0., 40.,  0.,  0.],
    [42.,  8.,  0.,  0., 28.,  0.,  0.,  0., 42.,  0., 29., 40.,  0.,  0.,  0.],
    [ 0., 21.,  0., 28.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 62., 65.,  0., 26.],
    [ 0.,  0.,  0.,  0.,  0.,  0., 25., 10., 28.,  0.,  0.,  0.,  0.,  0.,  0.],
    [ 0.,  0., 31.,  0.,  0., 25.,  0., 32., 41.,  0., 50.,  0., 54.,  0.,  0.],
    [59.,  0., 62.,  0.,  0., 10., 32.,  0., 35., 73.,  0.,  0.,  0.,  0.,  0.],
    [29.,  0.,  0., 42.,  0., 28., 41., 35.,  0.,  0., 46.,  0.,  0.,  0.,  0.],
    [ 0.,  0., 11.,  0.,  0.,  0.,  0., 73.,  0.,  0.,  0.,  0., 40.,  0.,  0.],
    [ 0., 25.,  0., 29.,  0.,  0., 50.,  0., 46.,  0.,  0.,  0., 40.,  9., 13.],
    [25.,  0.,  0., 40., 62.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
    [ 0.,  0., 40.,  0., 65.,  0., 54.,  0.,  0., 40., 40.,  0.,  0., 33., 40.],
    [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0., 33.,  0.,  9.],
    [ 0., 25.,  0.,  0., 26.,  0.,  0.,  0.,  0.,  0., 13.,  0., 40.,  9.,  0.]
])

# print(distances)

my_delays = np.array([
    [0.        , 0.        , 0.        , 0.005126  , 0.        , 0.        , 0.        , 0.00037787, 0.018658  , 0.        , 0.        , 0.0094491 , 0.        , 0.        , 0.        ],
    [0.        , 0.        , 0.        , 0.017342  , 0.0046723 , 0.        , 0.        , 0.        , 0.        , 0.        , 0.014451  , 0.        , 0.        , 0.        , 0.030107  ],
    [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.0056004 , 0.0084535 , 0.        , 0.025679  , 0.        , 0.        , 0.019839  , 0.        , 0.        ],
    [0.005126  , 0.017342  , 0.        , 0.        , 0.0017569 , 0.        , 0.        , 0.        , 0.0065448 , 0.        , 0.025474  , 0.012737  , 0.        , 0.        , 0.        ],
    [0.        , 0.0046723 , 0.        , 0.0017569 , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.025728  , 0.0057342 , 0.        , 0.008132  ],
    [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.017773  , 0.013941  , 0.029756  , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
    [0.        , 0.        , 0.0056004 , 0.        , 0.        , 0.017773  , 0.        , 0.016226  , 0.012208  , 0.        , 0.023744  , 0.        , 0.011137  , 0.        , 0.        ],
    [0.00037787, 0.        , 0.0084535 , 0.        , 0.        , 0.013941  , 0.016226  , 0.        , 0.027989  , 0.0057436 , 0.        , 0.        , 0.        , 0.        , 0.        ],
    [0.018658  , 0.        , 0.        , 0.0065448 , 0.        , 0.029756  , 0.012208  , 0.027989  , 0.        , 0.        , 0.0084419 , 0.        , 0.        , 0.        , 0.        ],
    [0.        , 0.        , 0.025679  , 0.        , 0.        , 0.        , 0.        , 0.0057436 , 0.        , 0.        , 0.        , 0.        , 0.025214  , 0.        , 0.        ],
    [0.        , 0.014451  , 0.        , 0.025474  , 0.        , 0.        , 0.023744  , 0.        , 0.0084419 , 0.        , 0.        , 0.        , 0.039982  , 0.030706  , 0.012824  ],
    [0.0094491 , 0.        , 0.        , 0.012737  , 0.025728  , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
    [0.        , 0.        , 0.019839  , 0.        , 0.0057342 , 0.        , 0.011137  , 0.        , 0.        , 0.025214  , 0.039982  , 0.        , 0.        , 0.015008  , 0.014349  ],
    [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.030706  , 0.        , 0.015008  , 0.        , 0.01096   ],
    [0.        , 0.030107  , 0.        , 0.        , 0.008132  , 0.        , 0.        , 0.        , 0.        , 0.        , 0.012824  , 0.        , 0.014349  , 0.01096   , 0.        ]])

# print(my_delays)


def get_constraints(file_name: str):

    # Receiving and reading the data
    # my_distances = genfromtxt(file_path, delimiter=',')
    if file_name == 'distance.csv':
        distances = my_distances
    elif file_name == 'delay.csv':
        distances = my_delays
    else:
        print("File not found")



    # List of cities
    # cities = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'][:4]
    cities = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O']
    start_city = cities[0]
    destination_city = cities[-1]

    # Distance between cities (replace with actual distances)
    # distances = my_distances[:4, :4]
    # distances = my_distances
    # delays = my_delays
    # distances[1, 3] = 6
    # distances[3, 1] = 6

    # Find the maximum distance
    max_distance = np.max(distances)
    # Update main diagonal elements
    np.fill_diagonal(distances, max_distance + 1)
    # print("distances:")
    # print(distances)

    # Number of cities
    num_cities = len(cities)

    # Inequality Constraints:

    # Constraint coefficients for exactly zero or one outgoing edge from each inner city(except for A, O)
    A_outgoing = []
    b_outgoing = []
    for i_index, i in enumerate(cities[1:-1]):  # Exclude the last city
        # print(i_index, i)
        row = np.zeros(num_cities ** 2)
        rhs_binary = np.zeros(num_cities-2) # to count # of outgoing edges from each inner cities, B, C, ..., N.
        rhs_binary[i_index] = -1 # outgoing = incoming, so same rhs binaries
        for j in cities:
            if j != i and distances[cities.index(i), cities.index(j)] > 0:
                j_index = cities.index(j)
                row[num_cities * cities.index(i) + cities.index(j)] = 1
        row = np.concatenate((row, rhs_binary))
        A_outgoing.append(row)
        b_outgoing.append(0)
    # print("A_outgoing:")
    # print(np.array(A_outgoing))

    # Constraint coefficients for exactly zero or one incoming edge from each inner city(except for A, O)
    A_incoming = []
    b_incoming = []

    for j_index, j in enumerate(cities[1:-1]):  # Exclude the last city
        row = np.zeros(num_cities ** 2)
        rhs_binary = np.zeros(num_cities-2) # to count # of incoming edges from each inner cities, B, C, ..., N.
        rhs_binary[j_index] = -1 # outgoing = incoming, so same rhs binaries
        for i_index, i in enumerate(cities):
            if i != j and distances[cities.index(i), cities.index(j)] > 0:
                row[num_cities * cities.index(i) + cities.index(j)] = 1
        row = np.concatenate((row, rhs_binary))
        A_incoming.append(row)
        b_incoming.append(0)
    # print("A_incoming:")
    # print(np.array(A_incoming))

    A = np.vstack((A_outgoing, A_incoming))
    b = np.concatenate((b_outgoing, b_incoming))
    # print("\nInequality Constraints (A):")
    # print(np.array(A))
    # print("\nInquality Bounds (b):")
    # print(np.array(b))

    # Equality Constraints
    A_eq = []
    b_eq = []

    # Destination city constraint for having 0 outgoing edges
    row = np.zeros(num_cities ** 2)
    rhs_binary = np.zeros(num_cities-2)
    for j in cities:
        if distances[cities.index(destination_city), cities.index(j)] > 0:
            row[num_cities * cities.index(destination_city) + cities.index(j)] = 1
    row = np.concatenate((row, rhs_binary))
    A_eq.append(row)
    b_eq.append(0)
    # print("A_eq:")
    # print(np.array(A_eq))


    # Starting city constraint for having zero incoming edges
    row = np.zeros(num_cities ** 2)
    rhs_binary = np.zeros(num_cities-2)
    for i in cities:
        if distances[cities.index(i), cities.index(start_city)] > 0:
            row[num_cities * cities.index(i) + cities.index(start_city)] = 1
    row = np.concatenate((row, rhs_binary))
    A_eq.append(row)
    b_eq.append(0)
    # print("A_eq:")
    # print(np.array(A_eq))

    # Destination city constraint for having 1 incoming edge
    row = np.zeros(num_cities ** 2)
    rhs_binary = np.zeros(num_cities-2)
    for i in cities:
        if distances[cities.index(i), cities.index(destination_city)] > 0:
            row[num_cities * cities.index(i) + cities.index(destination_city)] = 1
    row = np.concatenate((row, rhs_binary))
    A_eq.append(row)
    b_eq.append(1)
    # print("A_eq:")
    # print(np.array(A_eq))

    # Starting city constraint for having 1 outgoing edge
    row = np.zeros(num_cities ** 2)
    rhs_binary = np.zeros(num_cities-2)
    for j in cities:
        if distances[cities.index(start_city), cities.index(j)] > 0:
            row[num_cities * cities.index(start_city) + cities.index(j)] = 1
    row = np.concatenate((row, rhs_binary))
    A_eq.append(row)
    b_eq.append(1)
    # print("A_eq:")
    # print(np.array(A_eq))

    Ae = np.vstack((A, A_eq)) # stacking all LHS of constraints together
    be = np.concatenate((b, b_eq)) # stacking all RHS of constraints together
    A_ineq = None
    b_ineq = None


    return distances, A_ineq, b_ineq, Ae, be

if __name__ == "__main__":

    distances_received, A_ineq, b_ineq, Ae, be = get_constraints('distance.csv')
    print("distances_received :")
    print(distances_received)

    print("\nEquality Constraints (Ae):")
    print(np.array(Ae))
    print("\nEquality Bounds (be):")
    print(np.array(be))
    print("Ae.shape: ", np.array(Ae).shape)

